title: "ITR Private Assistant"
platform: openai
openai_apikey: "***"
watsonx_apikey: "***"
model_params:
  decoding_method: "greedy"
  repetition_penalty: 1.05
  stop_sequences:
  - "<|user|>"
  - "<|endoftext|>"
  min_new_tokens: 1
  max_new_tokens: 100
